version: '3'

services:
  clock-in-bot:
    build: ./
    restart: always
    env_file:
      - .env
    ports:
      - "12121:80"
    volumes:
      - clockinbot:/usr/src/app
    networks:
      - default

volumes:
  clockinbot: